### ISSUE TITLE
Absence of `ROOT_HISTORY_EXPIRY` update mechanism in `StateBridge` contract

### ISSUE THREAD

**Issue by iamrecursion** [worldcoin/world-id-state-bridge#33]
The `OpWorldID` contract uses the `onlyOwner` modifier for the functions `receiveRoot(...)` and `setRootHistoryExpiry(...)`, as illustrated below.

```solidity

contract OpWorldID is WorldIDBridge, CrossDomainOwnable3, IOpWorldID {
    ...
    function receiveRoot(...) external virtual onlyOwner {
        _receiveRoot(newRoot, supersedeTimestamp);
    }

   ////////////////////////////////////////////////////////////////
   // @audit only the StateBridge contract can call this function
   ////////////////////////////////////////////////////////////////
   function setRootHistoryExpiry(...) public virtual override onlyOwner {
        _setRootHistoryExpiry(expiryTime);
    }
}

```

The `receiveRoot(...)` function is called by the `StateBridge` contract (the owner) to forward the latest `root` to the bridged WorldID. In contrast, `setRootHistoryExpiry(...)` updates the expiration time for a `root`. However, the `StateBridge` contract does not have a function for calling `setRootHistoryExpiry(...)` to update the expiration time. To invoke this function, the owner of `StateBridge` must transfer ownership of `OpWorldID` to another contract or to a local Optimism EOA.

**Comment by iamrecursion** [comment]
One potential solution is:

> Add an external function in the `StateBridge` contract that can only be called by the owner to invoke `OpWorldID.setRootHistoryExpiry(...)`. 

This may not be the best option, as we could also bifurcate ownership to allow a separate owner on optimism. @dcbuild3r will have more idea than me here.

**Comment by iamrecursion** [comment]
We may also want to examine setting things via the `StateBridge` to keep these in sync across chains.

**Comment by dcbuild3r** [comment]
if we introduce another `Ownable` it will be a bit weird since `CrossDomainOwnable3` inherits from it and all variables and fn signatures will collide. I think it is better to add a function to `world-id-state-bridge` which does a cross-domain call to OpWorldID to `setRootHistoryExpiry`.

**Comment by dcbuild3r** [comment]
will do!
