### ISSUE TITLE
Opportunities to earn

### ISSUE THREAD

**Issue by Bhaney44** [worldcoin/world-id-state-bridge#84]
Hi,

I hope all is well. I am looking for opportunities to earn WorldCoin. Is the project team currently offering any such opportunities for OSS developers? 

Thanks,

Brian

**Comment by r3ld3v** [comment]
Hello and thank’s for the interest!

All our open positions can be found [here](https://worldcoin.org/careers). I’d encourage you to apply to anything you see that might be of interest to you.

**Comment by Bhaney44** [comment]
Ok, thank you.
